const projects = [
    {
      id: 0,
      url: 'https://carmentraining.netlify.app/',
      title: 'Carmentraining',
      description: 'Página web para entrenadora personal',
      list: ['Html', 'Css', 'Javascript'].join(' '),
      image: './assets/carmentraining-white.jpg',
      imageModal: './assets/carmentraining.jpg',
      client: 'Carmentraining',
      date: 'Julio 2022',
      projectType: 'Página web',
    },
    
    {
      id: 1,
      url: 'https://text-to-speech-carmen.netlify.app/',
      title: 'Text to Speech',
      description: 'Convierte el texto a sonido',
      list: ['Html', 'Css', 'Javascript'].join(' '),
      image: './assets/text-synth-white.jpg',
      imageModal: './assets/text-synth.jpg',
      client: 'Público',
      date: 'Agosto 2022',
      projectType: 'Página web',
    },
    
    {
      id: 2,
      url: 'https://calculator-carmen.netlify.app/',
      title: 'Calculadora',
      description: 'Calculatora',
      list: ['Html', 'Css', 'Javascript', 'React'].join(' '),
      image: './assets/calculator-white.jpg',
      imageModal: './assets/calculator.jpg',
      client: 'Público',
      date: 'Agosto 2022',
      projectType: '',
    },
    
    {
      id: 3,
      url: 'https://3-en-raya-carmen.netlify.app/',
      title: 'Play "3 en raya" ',
      description: 'Un simple juego para pasar el rato',
      list: ['Html', 'Css', 'Javascript'].join(' '),
      image: './assets/3-en-raya-white.jpg',
      imageModal: './assets/3-en-raya.jpg',
      client: 'Público',
      date: 'Agosto 2022',
      projectType: 'Un simple juego para pasar el rato',
    },
    
    {
      id: 4,
      url: 'https://weather-current-app-react.netlify.app/',
      title: 'Weather Current App',
      description: 'Aplicación de clima actual con React',
      list: ['Html', 'Css', 'Javascript', 'React'].join(' '),
      image: './assets/weather-white.jpg',
      imageModal: './assets/weather.jpg',
      client: 'Public',
      date: 'Agosto 2022',
      projectType: 'Aplicación de clima actual',
    },
  
    {
      id: 5,
      url: 'https://convert-audio-to-text.netlify.app/',
      title: 'Convert Audio To Text',
      description: 'Convierte audio en texto y descarga el archivo',
      list: ['Html', 'Css', 'Javascript'].join(' '),
      image: './assets/convert-audio-to-text-white.jpg',
      imageModal: './assets/convert-audio-to-text.jpg',
      client: 'Público',
      date: 'Agosto 2022',
      projectType: 'Página web',
    },
  
    {
      id: 6,
      url: 'https://piedra-papel-tijera-app.netlify.app/',
      title: 'Play rock, paper or scissors',
      description: 'Traditional game: Rock, paper, scissors',
      list: ['Html', 'Css', 'Javascript'].join(' '),
      image: './assets/piedra-papel-tijera-white.jpg',
      imageModal: './assets/piedra-papel-tijera.jpg',
      client: 'Public',
      date: 'Mayo 2022',
      projectType: 'App',
    },
  
    {
      id: 7,
      url: 'https://movies-app-carmenfrontdev.netlify.app/',
      title: 'Movies App',
      description: 'Aplicación para ver películas populares y descripciones de estas películas, ver por categoría y guardar tus favoritas.',
      list: ['Html', 'Css', 'Javascript'].join(' '),
      image: './assets/movies-white.jpg',
      imageModal: './assets/movies.jpg',
      client: 'Publico',
      date: 'Septiembre 2022',
      projectType: 'Página web',
    },
  
    {
      id: 8,
      url: 'https://calculator-without-react.netlify.app/',
      title: 'Calculator',
      description: 'Calculator website',
      list: ['Html', 'Css', 'Javascript'].join(' '),
      image: './assets/calculator-sin-react-white.jpg',
      imageModal: './assets/calculator-sin-react.jpg',
      client: 'Publico',
      date: 'Mayo 2022',
      projectType: 'Aplicación web',
    },
  
    {
      id: 9,
      url: 'https://juego-del-ahorcado-carmenfrontdev.netlify.app/',
      title: 'Hanged',
      description: 'Classic game The hanged',
      list: ['Html', 'Css', 'Javascript'].join(' '),
      image: './assets/hanged-white.jpg',
      imageModal: './assets/hanged.jpg',
      client: 'Publico',
      date: 'Octubre 2022',
      projectType: 'Game',
    },
  
    {
      id: 10,
      url: 'https://maquetacion-con-tailwind.netlify.app/',
      title: 'Traveling...',
      description: 'Página web con Tailwind 3.0',
      list: ['Html', 'Tailwind', 'Javascript'].join(' '),
      image: './assets/viajando-white.jpg',
      imageModal: './assets/viajando.jpg',
      client: 'Publico',
      date: 'Noviembre 2022',
      projectType: 'Page',
    },
  
    {
      id: 11,
      url: 'https://lista-de-tareas-carmenfrontdev.netlify.app/',
      title: 'Lista de tareas',
      description: 'Agrega tus tareas pendientes, marca las terminadas y elimina la que quieras',
      list: ['Html', 'Css', 'Javascript', 'React'].join(' '),
      image: './assets/tareas-white.jpg',
      imageModal: './assets/tareas.jpg',
      client: 'Publico',
      date: 'Noviembre 2022',
      projectType: 'Website',
    },
  
    {
      id: 12,
      url: 'https://decodifica-la-palabra.netlify.app/',
      title: 'Decodifica las palabras',
      description: 'Juego de palabras desordenadas',
      list: ['Html', 'Sass', 'Javascript'].join(' '),
      image: './assets/decodificar-white.jpg',
      imageModal: './assets/decodificar.jpg',
      client: 'Publico',
      date: 'Noviembre 2022',
      projectType: 'Juego',
    },
  
    {
      id: 13,
      url: 'https://juego-de-memoria-imagenes.netlify.app/',
      title: 'Juego de memoria',
      description: 'Encuentra la pareja de imágenes',
      list: ['Html', 'Sass', 'Javascript'].join(' '),
      image: './assets/memoria-imagenes-white.jpg',
      imageModal: './assets/memoria-imagenes.jpg',
      client: 'Publico',
      date: 'Noviembre 2022',
      projectType: 'Juego',
    },
  
    {
      id: 14,
      url: 'https://adivina-la-bandera.netlify.app/',
      title: 'Adivina la bandera',
      description: 'Adivina a que país pertenece la bandera',
      list: ['Html', 'Sass', 'Javascript'].join(' '),
      image: './assets/adivina-bandera-white.jpg',
      imageModal: './assets/adivina-bandera.jpg',
      client: 'Publico',
      date: 'Noviembre 2022',
      projectType: 'Juego',
    },
  
    {
      id: 15,
      url: 'https://platzifood-carmenfrontdev.netlify.app/',
      title: 'PlatziFood',
      description: 'Página de comidas hecha con Tailwind',
      list: ['Html', 'Tailwind', 'AlpineJs'].join(' '),
      image: './assets/platzifood-white.jpg',
      imageModal: './assets/platzifood.jpg',
      client: 'Publico',
      date: 'Noviembre 2022',
      projectType: 'Página web',
    },
  
    {
      id: 16,
      url: 'https://homesmart-carmenfrontdev.netlify.app/',
      title: 'HomeSmart',
      description: 'Página de muebles hecha con Tailwind',
      list: ['Html', 'Tailwind'].join(' '),
      image: './assets/homesmart-white.jpg',
      imageModal: './assets/homesmart.jpg',
      client: 'Publico',
      date: 'Noviembre 2022',
      projectType: 'Página web',
    },
  
    {
      id: 17,
      url: 'https://platzi-conf-carmenfrontdev.netlify.app/',
      title: 'PlatziConf',
      description: 'Maquetación con Bootstrap',
      list: ['Html', 'Css', 'Javascript', 'Bootstrap'].join(' '),
      image: './assets/platziconf-white.jpg',
      imageModal: './assets/platziconf.jpg',
      client: 'Publico',
      date: 'Diciembre 2022',
      projectType: 'Página web',
    },
  
    {
      id: 18,
      url: 'https://design-and-development.netlify.app/',
      title: 'Diseño | Desarrollo web',
      description: 'Empresa de diseño y desarrollo de páginas o sitios web',
      list: ['Html', 'Css', 'Javascript', 'Bootstrap'].join(' '),
      image: './assets/diseño-desarrollo-white.jpg',
      imageModal: './assets/diseño-desarrollo.jpg',
      client: 'Publico',
      date: 'Diciembre 2022',
      projectType: 'Sitio web',
    },
  ];